server:
  port: 8080

spring:
  application:
    name: springbootdemo

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 1000

  rabbitmq:
    host: 117.48.196.40
    port: 5672
    username: user
    password: password

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyk?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zhoustr1
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
    num-tests-per-eviction-run: 5
    remove-abandoned: true
    remove-abandoned-timeout: 180

mybatis:
  type-aliases-package: com.example.springbootdemo.entity
  mapper-locations: classpath:mapper/*Mapper.xml